name: Publish VS Code Extensions

on:
  push:
    branches:
     - linux

jobs:
  publish:
     runs-on:  ubuntu-latest
     steps:
       - name: Publish to Visual Studio Marketplace
       - uses: actions/checkout@v2
         with:
            ref: linux
       - uses: actions/setup-node@v1
         with :
           node-version: 16.16.0
       - run: npm install && npm install -g @vscode/vsce
       - name: Package VSIX
       - run: |
           publisher=$(jq -r '.publisher' package.json)
           version=$(jq -r '.version' package.json)
           vsce package --target linux-x64 linux-arm64 linux-armhf alpine-x64 alpine-arm64 --out $publisher-$version.vsix
       - name : Upload VSIX
       - uses: actions/upload-artifact@v2
         with:
            name: vsix
            path: '*.vsix'
